syntax = "proto3";
package metrics;

option go_package = "generated/proto";

// CPU
message CoreCPUMetrics {
    double userUtilization = 1;
    double systemUtilization = 2;
    double idleUtilization = 3;
    double ioWait = 4;
}

message CPUMetrics {
    bool isMultipleCores = 1;
    repeated CoreCPUMetrics cores = 2;
}


// MEMORY

message MemoryMetrics {
    uint64 totalRam = 1;
    uint64 usedRam = 2;
    uint64 freeRam = 3;
    uint64 availableRam = 4;
    double memoryUtilization = 5;
    uint64 totalSwap = 6;
    uint64 usedSwap = 7;
}


// NETWORK

message NetworkInterfaceMetrics {
    uint64 rxBytes = 1;
    uint64 txBytes = 2;
    uint64 txPackets = 3;
    uint64 rxPackets = 4;
    uint64 packetLoss = 5;
    string interfaceName = 6;
}

message NetworkMetrics {
    bool isMultipleInterfaces = 1;
    repeated NetworkInterfaceMetrics networkInterfaceMetrics = 2;
}


// DISK

message PartitionMetrics {
    string device = 1;
    string mountpoint = 2;
    string fstype = 3;
}

message DiskMetrics {
    uint64 totalDisk = 1;
    uint64 freeDisk = 2;
    uint64 usedDisk = 3;
    double diskUsage = 4;
    uint64 inodesTotal = 5;
    uint64 inodesUsed = 6;
    uint64 inodesFree = 7;
    double inodesUsedPercent = 8;
    repeated PartitionMetrics partitionMetrics = 9;
}


// CONNECTION

message MetricsResponse {
    MemoryMetrics memoryMetrics = 1;
    CPUMetrics cpuMetrics = 2;
    NetworkMetrics networkMetrics = 3;
    DiskMetrics diskMetrics = 4;
}

message MetricsRequest {
    bool multipleCores = 1;
    bool multipleInterfaces = 2;
}

enum ConnectionStatus {
    UNKNOWN = 0;
    ACCEPTED = 1;
    DENIED = 2;
}

message ConnectionRequest {
    string password = 1;
}

message ConnectionResponse {
    ConnectionStatus status = 1;
    string name = 2;
}

service MetricsService {
    rpc GetMetrics(MetricsRequest) returns (MetricsResponse) {}
    rpc Connect(ConnectionRequest) returns (ConnectionResponse) {}
}